import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layouts/Layout";
import styles from "../styles/Home.module.css";

export default function Contact() {
  return (
    <Layout>
      <Head>
        <title>Contact Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Layout>
  );
}
